name: l1metml
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - pytables
  - uproot
  - tensorflow=2.5.0
  - pandas
  - h5py
  - tqdm
  - scikit-learn
  - pip
  - pip:
    - setGPU
    - mplhep
    - git+https://github.com/google/qkeras#egg=qkeras
    - git+https://github.com/jmduarte/hls4ml@l1metml#egg=hls4ml[profiling]
